# Site settings
title: MolView Blog
email: info@molview.org
description: MolView is an intuitive, Open-Source web-application to make chemistry and biology more awesome!
baseurl: ""
url: "http://blog.molview.org"
twitter_username: molview
github_username:  molview

# Build settings
markdown: kramdown
